### ISSUE TITLE
module error

### ISSUE THREAD

**Issue by reisraff** [kmahyyg/mremoteng-decrypt#5]
```
$ python3 mremoteng-decrypt-master/mremoteng_decrypt.py -s 'b64' -p 'common_pass'
Traceback (most recent call last):
  File "mremoteng-decrypt-master/mremoteng_decrypt.py", line 49, in <module>
    main()
  File "mremoteng-decrypt-master/mremoteng_decrypt.py", line 45, in main
    plaintext = cipher.decrypt_and_verify(ciphertext, tag)
  File "/usr/lib/python3/dist-packages/Cryptodome/Cipher/_mode_gcm.py", line 504, in decrypt_and_verify
    self.verify(received_mac_tag)
  File "/usr/lib/python3/dist-packages/Cryptodome/Cipher/_mode_gcm.py", line 456, in verify
    raise ValueError("MAC check failed")
ValueError: MAC check failed
```

**Comment by kmahyyg** [comment]
-p is optional, you should read about readme.
